### ISSUE TITLE
Launch weblogic from fx-log

### ISSUE THREAD

**Issue by lwouis** [joffrey-bion/fx-log#1]
Instead of launching the server through `ant start`, explore launching it through fx-log, so no UI is visible to the user. Since this would mean we work with the live stream instead of the archive file, there are consequences such as: better perf (i.e. no disk access), no history (i.e. no access to previous logs, or random logs). This would be a feature in addition to reading the server.log file.

You would start the server and be connected automatically to the stream, or just launch fx-log and manually target a file.

Some notes:
-  Consume the sys.out/sys.err streams directly instead of consuming the file on the harddrive
- Start/Stop the server process from within the fx-log process
- `ant start` launches a .cmd file internally which launches the server. This means we need to access what's inside directly instead of calling the ant target.

**Comment by mebubo** [comment]
Hi guys!

Launching processes and redirecting streams, wouldn't that be reinventing a shell? ;)

```
$ ant start or whatever | fx-log
```

**Comment by joffrey-bion** [comment]
@mebubo Not exactly. Using a standard shell redirection would leave the shell window open in addition to fx-log's, which is not very convenient.

**Comment by lwouis** [comment]
@mebubo have a look at ant start, and you will understand why piping doesn't work here :/

**Comment by mebubo** [comment]
@lwouis if the command does not produce the output you are interested in, that's hardly shell's or fx-log's problem.

Do you suggest that fx-log extract text output from spawned cmd windows?

**Comment by joffrey-bion** [comment]
@mebubo No he suggests that the spawned cmd window is not spawned at all. The process would be spawned directly from FX Log without cmd window.

**Comment by mebubo** [comment]
@joffrey-bion @lwouis Then starting _that_ process in a shell and piping its output would work just as well.

**Comment by joffrey-bion** [comment]
@mebubo Are you talking about fx-log itself? I think Louis' point is to avoid having the current weblogic console window and the fx-log window. However, this console window is basically weblogic' s process, and closing it kills the server altogether. Therefore, if we want to get rid of the window, we also need to find a way of stopping the server.

Currently, Ant starts a cmd file starting weblogic which creates that console window. I' d like to start fx-log directly from Ant, with a param to make it launch the right server (I don't see where the pipe would be of any use here, since we can read server.log just as well). But anyway I think this might not be possible. We need to dig a little bit inside the start_server.cmd files.

As this is not the prime purpose of FX Log, this feature is really not my priority right now. We can still deal with the 2 windows. However, a command line parameter for the file to open is basic and necessary, and this is one of the next features.

**Comment by mebubo** [comment]
@joffrey-bion If we are not talking about magically reading the output off of a spawned cmd window, then it looks like this proposed fx-log enhancement boils down to:

 1) being able to start/stop a process
 2) being able to redirect the processes's output and error streams
 3) being able to read a stream in fx-log

I just wanted to point out that 1) and 2) are what traditional shells are _for_ and what they are good at. 

So it would be enough to implement 3) (read the stdin) in fx-log; 1) and 2) can be handled by a shell.

**Comment by joffrey-bion** [comment]
@mebubo We don't need 2) nor 3). We just need to start weblogic and fx-log, but without weblogic's console, and we need a way to stop weblogic when required.
I feel like the Windows "start-as-a-service" approach for weblo would be doing the job, or just digging into the cmd files to find what opens the annoying log window in the first place and bypass it.
Anyway, I also think this has nothing to do with fx-log.

(Reading stdin from fx-log might be a useful enhancement at some point, but not necessay for us in any case since we can read server.log, which btw differs a little bit from the weblo console output)
