### ISSUE TITLE
Scrolling down on mouse causes Scroll button to uncheck

### ISSUE THREAD

**Issue by lwouis** [joffrey-bion/fx-log#38]
Scrolling down while already at the bottom shouldn't uncheck the "Scroll" button. Also the scroll button should be called something like "Follow tail" (see other software for inspiration).

**Comment by joffrey-bion** [comment]
The button unchecks on any scroll event. This is a problem because, indeed, scrolling down while at the bottom shouldn't stop it. What's more, scrolling all the way down should actually activate the followTail mechanism.

The button is now poorly named because its functions changed without changing the label :D This needs an update too, indeed.
