### ISSUE TITLE
Project first import issue on Intellij

### ISSUE THREAD

**Issue by lwouis** [joffrey-bion/fx-log#6]
When you import the project as a Gradle project on Intellij, you get issues because it tries to build before the import is finished.

I think a quick workaround would be to add a `gradle.properties` file with the following content:

```
bintrayUsername: .
bintrayApiKey: .
bintrayRepoApps: .
```

**Comment by joffrey-bion** [comment]
@lwouis Indeed, I noticed this and will try to find a solution. This quick workaround cannot work for me because this local project file would take precedence over my user level `gradle.properties`.

Typically, these variables are only used for releases upload to bintray, so they're of no use to contributors. It is weird that Gradle fails even if they are not used. They should not try to access these variables if the related task is not executed.
