### ISSUE TITLE
Add the latest download badge to the Github page

### ISSUE THREAD

**Issue by lwouis** [joffrey-bion/fx-log#83]
Badge

 [ ![Download](https://api.bintray.com/packages/joffrey-bion/applications/fx-log/images/download.svg) ](https://bintray.com/joffrey-bion/applications/fx-log/_latestVersion)

Markdown code

`[ ![Download](https://api.bintray.com/packages/joffrey-bion/applications/fx-log/images/download.svg) ](https://bintray.com/joffrey-bion/applications/fx-log/_latestVersion)`

**Comment by joffrey-bion** [comment]
This badge leads to the same page as the bintray one, which is still not a direct download. We could add it to the download section anyway, just for people to have something more flashy to click on, but there's not as much gain as a direct download button.

That being said, once #73 is done, we can't have a single direct download, because different people might want different download options. If we have a bunch of download links, I'd rather leave them in Bintray, where they belong.
